<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="fr" sourcelanguage="en">
<context>
    <name>generals</name>
    <message>
        <location filename="../XTFLog_Checker_dock_panel.py" line="44"/>
        <source>Show errors</source>
        <translation>Afficher erreures</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dock_panel.py" line="45"/>
        <source>Show warnings</source>
        <translation>Afficher avertissements</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="45"/>
        <source>Create layer</source>
        <translation>Créer layer</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="48"/>
        <source>Cancel</source>
        <translation>Annuler</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="51"/>
        <source>Show error log</source>
        <translation>Afficher le log des erreurs</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="52"/>
        <source>Upload xtf-log file</source>
        <translation>Choisir chemin ou URL d&apos;un fichier XTF-Error-Log</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="53"/>
        <source>Show log for existing layer</source>
        <translation>Afficher le log des erreurs pour un layer existant</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="54"/>
        <source>Only layers created with this plugin can be selected</source>
        <translation>Seuls les layers créés avec ce plugin peuvent être sélectionnés</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="94"/>
        <source>No valid file</source>
        <translation>Fichier non valide</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="86"/>
        <source>Could not get a valid XTF-Log file from specified Url</source>
        <translation>Impossible d&apos;obtenir un fichier XTF-Log valide à partir de l&apos;URL spécifiée</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="94"/>
        <source>No valid XTF-Log file at specified Path</source>
        <translation>Aucun fichier XTF-Log valide au chemin d&apos;accès spécifié</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dock_panel.py" line="48"/>
        <source>Error log</source>
        <translation>XTFLog-Checker log des erreurs</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="155"/>
        <source>No Errors</source>
        <translation>Aucune erreur</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="155"/>
        <source>The selected XTF file contains no Ilivalidator-Errors, select another file.</source>
        <translation>Le fichier sélectionné ne contient aucune erreur du type IliVErrors, sélectionnez un autre fichier.</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="90"/>
        <source>Large file</source>
        <translation>Fichier de plus de 5 MB</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="90"/>
        <source>Processing of large XTF-Log files might take a while</source>
        <translation>Le traitement de fichiers volumineux peut prendre un certain temps</translation>
    </message>
</context>
</TS>
