<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="de" sourcelanguage="en">
<context>
    <name>generals</name>
    <message>
        <location filename="../XTFLog_Checker_dock_panel.py" line="44"/>
        <source>Show errors</source>
        <translation>Fehler anzeigen</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dock_panel.py" line="45"/>
        <source>Show warnings</source>
        <translation>Warnungen anzeigen</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="45"/>
        <source>Create layer</source>
        <translation>Layer erstellen</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="48"/>
        <source>Cancel</source>
        <translation>Abbrechen</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="51"/>
        <source>Show error log</source>
        <translation>Fehlerprotokoll anzeigen</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="52"/>
        <source>Upload xtf-log file</source>
        <translation>Pfad oder URL einer XTF-Error-Log Datei auswählen</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="53"/>
        <source>Show log for existing layer</source>
        <translation>Fehler-Log für vorhandenen Layer anzeigen</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="54"/>
        <source>Only layers created with this plugin can be selected</source>
        <translation>Nur mit diesem Plugin erstellte Layer können ausgewählt werden</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="94"/>
        <source>No valid file</source>
        <translation>Keine gültige Datei</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="86"/>
        <source>Could not get a valid XTF-Log file from specified Url</source>
        <translation>Es konnte keine gültige XTF-Log-Datei von der angegebenen URL abgerufen werden</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="94"/>
        <source>No valid XTF-Log file at specified Path</source>
        <translation>Keine gültige XTF-Log-Datei unter angegebenem Pfad</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dock_panel.py" line="48"/>
        <source>Error log</source>
        <translation>XTFLog-Checker Fehlerprotokoll</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="155"/>
        <source>No Errors</source>
        <translation>Keine Fehler</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="155"/>
        <source>The selected XTF file contains no Ilivalidator-Errors, select another file.</source>
        <translation>Die ausgewählte Datei enthält keine Fehler vom Typ IliVErrors, wählen Sie eine andere Datei.</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="90"/>
        <source>Large file</source>
        <translation>Datei grösser als 5 MB</translation>
    </message>
    <message>
        <location filename="../XTFLog_Checker_dialog.py" line="90"/>
        <source>Processing of large XTF-Log files might take a while</source>
        <translation>Die Verarbeitung grosser Dateien kann eine Weile dauern</translation>
    </message>
</context>
</TS>
